problem2
theonlymusya/sspp_homework pull request #3
Opened 2021-12-26 17:49 UTC by theonlymusya

2021-12-26 18:07 UTC, lberserq commented on problem2/long_long_problem2.c
> +			free(B[i]);
форматирование

2021-12-26 18:08 UTC, lberserq requested changes
ждем отчет

2021-12-26 19:04 UTC, theonlymusya commented
> 

Я приложила pdf, или его не видно?

2021-12-27 12:12 UTC, merged

2021-12-27 18:38 UTC, lberserq reviewed
Почему в замеры ключен вывод(printf)